openapi: '3.0.2'

info:
  title: Bayut API
  version: '1.0'
  x-twitter: 'https://x.com/bayut_api'
  x-linkedin: 'https://www.linkedin.com/in/bayut-api/'
  x-logo:
    url: https://bayutapi.com/imgs/logo/bayut-api-logo-dark.svg
  description: |
    Bayut API is a property finder API that allows you to search for real estate properties in the UAE by scraping data from Bayut's Website (https://bayut.com).
    
    You can gather data related to properties, agencies, agents, developers, amenities, transactions, etc…
  contact:
    name: Email
    email: bayut.restapi@gmail.com
    url: https://bayutapi.com

  termsOfService: https://bayutapi.com/terms_of_use.html


externalDocs:
  description: Read more
  url: 'https://bayutapi.com/documentation.html?utm_source=swagger_docs&utm_medium=external_docs&utm_campaign=api_reference'

servers:
  - url: https://bayut-api1.p.rapidapi.com

paths:

  /locations_search?query={query}:
    $ref: './paths/locations_search.yaml'

  /properties_search:
    $ref: './paths/properties_search.yaml'

  /property/{property_id}:
    $ref: './paths/property_info.yaml'


  /agencies_by_locations?locations_ids={locations_ids}:
    $ref: './paths/agencies_by_locations.yaml'

  /agencies_by_name?query={query}:
    $ref: './paths/agencies_by_name.yaml'

  /agency/{agency_id}:
    $ref: './paths/agency_info.yaml'

  /developers_search?query={query}:
    $ref: './paths/developers_search.yaml'


  /agents_by_name?query={query}:
    $ref: './paths/agents_by_name.yaml'

  /agents_by_filters:
    $ref: './paths/agents_by_filters.yaml'

  /agents_in_agency/{agency_id}:
    $ref: './paths/agents_in_agency.yaml'

  /agent/{agent_id}:
    $ref: './paths/agent_info.yaml'


  /transactions:
    $ref: './paths/transactions.yaml'

  /amenities_search?query={query}:
    $ref: './paths/amenities_search.yaml'

  
# components:
#   securitySchemes:
#     ApiKey: 
#       type: apiKey
#       in: header
#       name: x-rapidapi-key